# Generated by Django 6.0.1 on 2026-01-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_season_sidequest_timeofday_userquest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Both')], max_length=10, null=True)),
                ('cost_level', models.CharField(blank=True, choices=[('free', 'Free'), ('cheap', 'Cheap'), ('medium', 'Medium'), ('pricey', 'Pricey')], max_length=10, null=True)),
                ('social_type', models.CharField(blank=True, choices=[('solo', 'Solo'), ('group', 'With others'), ('either', 'Either')], max_length=10, null=True)),
                ('effort_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='tasks.category')),
                ('seasons', models.ManyToManyField(blank=True, to='tasks.season')),
                ('times_of_day', models.ManyToManyField(blank=True, to='tasks.timeofday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
