# Generated by Django 6.0.1 on 2026-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidequest',
            name='duration_level',
            field=models.CharField(choices=[('short', 'Short (< 2 hours)'), ('medium', 'Medium (a day)'), ('long', 'Long (days/weeks)')], default='short', max_length=10),
            preserve_default=False,
        ),
    ]
