# Generated by Django 6.0.1 on 2026-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_sidequest_duration_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidequest',
            name='duration_level',
            field=models.CharField(choices=[('short', 'Short (< 2 hours)'), ('medium', 'Medium'), ('long', 'Long (days/weeks)')], max_length=20),
        ),
    ]
