# Generated by Django 6.0.1 on 2026-01-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_sidequest_duration_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='duration_level',
            field=models.CharField(blank=True, choices=[('short', 'Short (< 2 hours)'), ('medium', 'Medium'), ('long', 'Long (days/weeks)')], max_length=10, null=True),
        ),
    ]
