# Generated by Django 6.0.1 on 2026-01-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_userpreference_duration_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='location_type',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='social_type',
            field=models.CharField(blank=True, choices=[('solo', 'Solo'), ('group', 'With others')], max_length=10, null=True),
        ),
    ]
