# Generated by Django 6.0.1 on 2026-04-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_userpreference_location_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidequest',
            name='activity_type',
            field=models.CharField(choices=[('creative', 'Creative'), ('writing', 'Writing'), ('research', 'Research'), ('reading', 'Reading'), ('media', 'Media'), ('physical', 'Physical'), ('social', 'Social'), ('outdoor', 'Outdoor'), ('home', 'Home'), ('skill', 'Skill'), ('practical', 'Practical'), ('food', 'Food')], default='creative', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sidequest',
            name='categories',
            field=models.ManyToManyField(related_name='sidequests', to='tasks.category'),
        ),
    ]
